### ISSUE TITLE
HttpResponse.text is not populated with response body except for HTTP_STATUS 200

### ISSUE THREAD

**Issue by kmgoudarzi** [shaovoon/winhttp_examples#4]
# Issue

Other than for HTTP Response Status Code 200 the `HttpResponse.text` field is not populated with response returned by the remote server.   In many scenarios the response body contains error codes, json object and the like which are necessary for calling applications.

# Fix
Currently in the [WinHttpWrapper::HttpRequest::http](https://github.com/shaovoon/winhttp_examples/blob/a60c0eba342373a0cdbf8cdbc2e7debefe652039/WinHttpGet/WinHttpGet/WinHttpWrapper.cpp#L89)  the response body is only added to the `text` field when the HTTP_Response code is 200 

To fix this the while do/while loop [here](https://github.com/shaovoon/winhttp_examples/blob/a60c0eba342373a0cdbf8cdbc2e7debefe652039/WinHttpGet/WinHttpGet/WinHttpWrapper.cpp#L253) should be called irrespective of the Response Code returned.  

# Also 
Very nice and useful :-)

**Comment by shaovoon** [comment]
Thank you for reporting this bug. It is fixed with v1.0.2.

**Comment by kmgoudarzi** [comment]
Great - just eye balling the 1.0.2 code … shouldn’t the break statement on line 282 be removed to allow the default case to add the text and then fall through for other case to apply

**Comment by shaovoon** [comment]
I just pushed the change to let the code fall through. Please kindly check if it is okay.

**Comment by kmgoudarzi** [comment]
Looks good ... I was lost as.I was looking at the 1.0.2 branch but guess you made the fix to master

**Comment by shaovoon** [comment]
GitHub did not notify me when you put a thumb up. Now the v1.0.3 is up. Thanks!
